language: node_js
node_js:
  - node
cache:
    yarn: true
    directories:
      - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_57d4f9f85dfd_key -iv $encrypted_57d4f9f85dfd_iv -in fonts.tar.enc -out src/fonts/fonts.tar -d
  - tar xvf src/fonts/fonts.tar
script:
  - yarn build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY
  bucket: "wunderdog-site-v2"
  acl: public_read
  skip_cleanup: true
  local_dir: dist
branches:
  only:
    - master
