language: node_js
node_js:
  - node
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - unzip -P $zip_password fonts.zip -d src/fonts/
script:
  - yarn build
deploy:
  provider: s3
  region: eu-central-1
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY
  bucket: "wunderdog-site-v2"
  acl: public_read
  skip_cleanup: true
  local_dir: dist
branches:
  only:
    - master
